spring:
  datasource:
    url: jdbc:h2:mem:apilog;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate.ddl-auto: update
  h2:
    console.enabled: true
    console.path: /h2
server:
  port: 8080
